# Generated by Django 2.1.1 on 2018-09-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accomplishment_type', models.IntegerField(choices=[(0, 'Musical'), (1, 'Linguistic'), (2, 'Other')])),
            ],
        ),
    ]
